### ISSUE TITLE
やっていきの効果音→キュイィィン

### ISSUE THREAD

**Issue by cureseven** [pinkumohikan/isucon11-qualify-kaki-n#1]
# ISUCON11 予選！

レギュレーション
https://isucon.net/archives/55854734.html

参加規約
https://isucon.net/archives/55857411.html

当日マニュアル
https://gist.github.com/ockie1729/53589a0e8c979198b6231d8599153c70

# IP

```
app1 : 54.248.86.147
app2 : 35.73.140.15
app3 : 52.192.191.67
```

# netdata
app1 : http://54.248.86.147:19999
app2 : http://35.73.140.15:19999
app3 : http://52.192.191.67:19999

**Comment by pinkumohikan** [comment]
assetsのgzip_static配信で

https://portal.isucon.net/contestant/benchmark_jobs/32596

```
Marked At: 2021-08-21 18:16:24.436
Score: 94976
Score Breakdown: base=95018, deduction=42
```
